# What protocol to use when performing Git operations. Supported values: ssh, https.
git_protocol: ssh
# Set your desired Markdown renderer style. Available options are [dark, light, notty]. To set a custom style, refer to https://github.com/charmbracelet/glamour#styles
glamour_style: dark
# Allow glab to automatically check for updates and notify you when there are new updates.
check_update: false
# Whether or not to display hyperlink escape characters when listing items like issues or merge requests. Set to TRUE to display hyperlinks in TTYs only. Force hyperlinks by setting FORCE_HYPERLINKS=1 as an environment variable.
display_hyperlinks: false
# Default GitLab hostname to use.
host: gitlab.local
# Set to true (1) to disable prompts, or false (0) to enable them.
no_prompt: false
# Configuration specific for GitLab instances.
hosts:
  gitlab.local:
    api_protocol: http
    api_host: gitlab.local
    token: GITLABTOKEN
